### ISSUE TITLE
Reduce the png size

### ISSUE THREAD

**Issue by abchatra** [BrightWearables/pxt-microbit-brightboard#1]
This PNG is nearly 0.5 MB. https://github.com/BrightWearables/pxt-microbit-brightboard/blob/master/icon.png

Is it possible to reduce below 100k? This impacts network speed

**Comment by BrightWearables** [comment]
Yes, so sorry about that - I hadn't realized it was that large. I've swapped it out for one that's 11k. Thank you.

**Comment by BrightWearables** [comment]
Do I need to make a new release of the BrightBoard extension to incorporate the changed icon file, or does it automatically propagate?

**Comment by BrightWearables** [comment]
Sorry, too for the delay in responding. I hadn't set my Github notifications correctly. I've fixed it now, so I will see issues immediately.
